import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Welcome, GetCharacterResults } from '../types'

const Home: NextPage<{characters: Welcome[]}> = ({characters}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {characters.map((character) => {
      return <div id={character.name}>{character.name}
      <Image
      src={character.image}
      alt={character.name}
      width="200"
      height="200"
      />
      </div>
    })}
    </div>
  )
}

// runs when build app
// type defined when variable defined?
export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character")
  const { results }:GetCharacterResults = await res.json();

  return {
    props: {
      characters: results,
    }
  }
}

// run app in lambda functions - dynamic server rendernig website


export default Home
